# Generated by Django 2.1.5 on 2021-08-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20210806_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(default='nothing'),
        ),
    ]
