# Generated by Django 2.1.5 on 2021-08-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_page_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name_plural': 'Pages'},
        ),
    ]
